# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Run the welcome/run job in its own container
executors:
  default:
    description: daniel's docker image
  docker:
    - image: dseuss/cunda:10.1-baseA

jobs:
  run:
    desctiption: |
            "Awesome shit"
  steps:
    - run:
        command: echo "hello"
        name: says hello
