# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: dseuss/cunda:10.1-base
    steps:
      - checkout
      - run:
          command: echo "hello"
          name: says hello
      - run:
          command: pwd
      - run:
          command: ls
      - run:
          command: conda env create -f env-ubuntu.yml
      - run:
          command: source activate dingo
      - run:
          command: pip install pytest
      - run:
          command: pytest test/

